BACKGROUND_COLOR: darkgray
SCREEN_RES: [1920, 1080]
FRAME_RATE: 50
FIX_CROSS_COLOR: black
FIX_CROSS_TIME: 25
TRAINING_CSI: 10
NO_TRAINING_TRIALS: [5,1]
STIM_SIZE: 100
GO_TIME: 1000

STIM_DURATION_IN_FRAMES: 1
FRAMES_BETWEEN_STIMS: 25
REACTION_KEYS: ['space','d','k','f7']
REACTION_TIME: 50

TRENING: 15
EKSPERYMENT1: 20
EKSPERYMENT2: 10
EKSPERYMENT3: 10
EKSPERYMENT4: 10
